#!/bin/sh
####################################################################################################
#
# This is free and unencumbered software released into the public domain.
# 
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
# 
# In jurisdictions that recognise copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
# 
# For more information, please refer to <http://unlicense.org/>
#
####################################################################################################
#
# More information: 
#
# GitRepo: 
#
####################################################################################################

# HARDCODED VALUES ARE SET HERE

# If Y then prompts user to logout, if N then kill the loginwindow forcing a logout.
logoutPrompt=""

# CHECK TO SEE IF A VALUE WAS PASSED IN PARAMETER 4 AND, IF SO, ASSIGN TO "caCertLocation"
if [ "$4" != "" ] && [ "$logoutPrompt" == "" ];then
    logoutPrompt=$4
fi

####################################################################################################

##
# Error if variable logoutPrompt is empty
##
if [ "$logoutPrompt" == "" ]; then
	echo "Error:  No value was specified for the logoutPrompt variable or the file does not exist..."
	exit 1
fi

###
# Get the Username of the logged in user
###
loggedInUser=`/bin/ls -l /dev/console | /usr/bin/awk '{ print $3 }'`

##
# Delete the logged in users login.keychain
##
sudo rm -rf /Users/"$loggedInUser"/Library/Keychain/login.keychain
echo "Deleted the Login Keychain for "$loggedInUser"..."

##
# If logoutPrompt = Y then, prompt the user to logout, else kill the loginwindow
##

if [ "$logoutPrompt" == "Y" ]; then
	echo "Nice logout chosen.. prompting user "$loggedInUser"..."
	(osascript -e 'tell application "System Events" to log out')
else
	echo "Nice logout not chosen.. Killing loginwindow..."
	sudo killall loginwindow
fi
